#创建pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-nginx-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports: 
  - port: 80
    name: nginx-port
    targetPort: 80
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    test-cephrbd: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      test-cephrbd: "true"
  template:
    metadata:
      labels:
        test-cephrbd: "true"
    spec:
      containers:
       - name: nginx
         image: nginx:1.18.0
         volumeMounts:
           - name: nginx-file-pvc
             mountPath: /usr/share/nginx/html
      volumes:
       - name: nginx-file-pvc
         persistentVolumeClaim:
           claimName: rbd-nginx-pvc
           readOnly: false